CREATE TABLE [dbo].[10035_Display] (
    [AccountID]                    BIGINT          NULL,
    [ChannelID]                    BIGINT          NULL,
    [AdgroupGK]                    BIGINT          NULL,
    [CampaignGK]                   BIGINT          NULL,
    [SiteGK]                       BIGINT          NULL,
    [DomainGK]                     BIGINT          NULL,
    [ThemeGK]                      BIGINT          NULL,
    [LanguageGK]                   BIGINT          NULL,
    [CountryGK]                    BIGINT          NULL,
    [GeographicGK]                 BIGINT          NULL,
    [TargetPeriodStart]            DATETIME        NULL,
    [TargetPeriodEnd]              DATETIME        NULL,
    [OutputID]                     CHAR (32)       NULL,
    [DownloadedDate]               DATETIME        NULL,
    [Currency]                     NVARCHAR (10)   NULL,
    [Cost]                         DECIMAL (18, 2) NULL,
    [OriginalCost]                 DECIMAL (18, 2) NULL,
    [Clicks]                       INT             NULL,
    [Impressions]                  INT             NULL,
    [UniqueImpressions]            INT             NULL,
    [UniqueClicks]                 INT             NULL,
    [TotalConversionsOnePerClick]  INT             NULL,
    [TotalConversionsManyPerClick] INT             NULL,
    [Signups]                      INT             NULL,
    [Purchases]                    INT             NULL,
    [Leads]                        INT             NULL,
    [PageViews]                    INT             NULL,
    [Default]                      INT             NULL
);

