CREATE TABLE [dbo].[10035_BackEnd] (
    [AccountID]         BIGINT          NULL,
    [ChannelID]         BIGINT          NULL,
    [TrackerGK]         BIGINT          NULL,
    [GeoGK]             BIGINT          NULL,
    [GlobalTierGK]      BIGINT          NULL,
    [CampaignGK]        BIGINT          NULL,
    [TargetPeriodStart] DATETIME        NULL,
    [TargetPeriodEnd]   DATETIME        NULL,
    [Currency]          NVARCHAR (10)   NULL,
    [OutputID]          CHAR (32)       NULL,
    [DownloadedDate]    DATETIME        NULL,
    [ClientSpecific1]   DECIMAL (18, 2) NULL,
    [ClientSpecific2]   DECIMAL (18, 2) NULL,
    [ClientSpecific3]   DECIMAL (18, 2) NULL,
    [ClientSpecific4]   DECIMAL (18, 2) NULL,
    [ClientSpecific5]   DECIMAL (18, 2) NULL,
    [ClientSpecific6]   DECIMAL (18, 2) NULL,
    [ClientSpecific7]   DECIMAL (18, 2) NULL,
    [ClientSpecific8]   DECIMAL (18, 2) NULL,
    [ClientSpecific9]   DECIMAL (18, 2) NULL,
    [ClientSpecific10]  DECIMAL (18, 2) NULL,
    [ClientSpecific11]  DECIMAL (18, 2) NULL,
    [ClientSpecific12]  DECIMAL (18, 2) NULL,
    [ClientSpecific13]  DECIMAL (18, 2) NULL,
    [ClientSpecific14]  DECIMAL (18, 2) NULL,
    [ClientSpecific15]  DECIMAL (18, 2) NULL,
    [ClientSpecific16]  DECIMAL (18, 2) NULL,
    [ClientSpecific17]  DECIMAL (18, 2) NULL,
    [ClientSpecific18]  DECIMAL (18, 2) NULL,
    [ClientSpecific19]  DECIMAL (18, 2) NULL,
    [ClientSpecific20]  DECIMAL (18, 2) NULL
);

