CREATE TABLE [dbo].[10035_SocialChannel] (
    [AccountID]                 BIGINT          NULL,
    [ChannelID]                 BIGINT          NULL,
    [AdGK]                      BIGINT          NULL,
    [AdgroupGK]                 BIGINT          NULL,
    [CampaignGK]                BIGINT          NULL,
    [TrackerGK]                 BIGINT          NULL,
    [ImageCreativeGK]           BIGINT          NULL,
    [TitleCreativeGK]           BIGINT          NULL,
    [BodyCreativeGK]            BIGINT          NULL,
    [DisplayURLCreativeGK]      BIGINT          NULL,
    [DestinationURLCreativeGK]  BIGINT          NULL,
    [VideoCreativeGK]           BIGINT          NULL,
    [ThemeGK]                   BIGINT          NULL,
    [LanguageGK]                BIGINT          NULL,
    [CountryGK]                 BIGINT          NULL,
    [GeographicGK]              BIGINT          NULL,
    [LandingPageGK]             BIGINT          NULL,
    [TargetCountryGK]           BIGINT          NULL,
    [TargetCityGK]              BIGINT          NULL,
    [TargetEducationGK]         BIGINT          NULL,
    [TargetMaritalStatusGK]     BIGINT          NULL,
    [TargetIntrestsGK]          BIGINT          NULL,
    [TargetGenderGK]            BIGINT          NULL,
    [TargetToAgeGroupGK]        BIGINT          NULL,
    [TargetFromAgeGroupGK]      BIGINT          NULL,
    [TargetLanguageGK]          BIGINT          NULL,
    [TargetWorkplaceGK]         BIGINT          NULL,
    [TargetMatchCountryGK]      BIGINT          NULL,
    [TargetMatchCityGK]         BIGINT          NULL,
    [TargetMatchEducationGK]    BIGINT          NULL,
    [TargetMatchLanguageGK]     BIGINT          NULL,
    [TargetMatchWorkplaceGK]    BIGINT          NULL,
    [TargetMatchMaritalStatus]  BIGINT          NULL,
    [TargetMatchIntrestsGK]     BIGINT          NULL,
    [TargetMatchGenderGK]       BIGINT          NULL,
    [TargetMatchToAgeGroupGK]   BIGINT          NULL,
    [TargetMatchFromAgeGroupGK] BIGINT          NULL,
    [TargetPeriodStart]         DATETIME        NULL,
    [TargetPeriodEnd]           DATETIME        NULL,
    [OutputID]                  CHAR (32)       NULL,
    [DownloadedDate]            DATETIME        NULL,
    [Currency]                  NVARCHAR (10)   NULL,
    [Cost]                      DECIMAL (18, 2) NULL,
    [OriginalCost]              DECIMAL (18, 2) NULL,
    [AveragePosition]           DECIMAL (18, 2) NULL,
    [SocialCost]                DECIMAL (18, 2) NULL,
    [Clicks]                    INT             NULL,
    [UniqueClicks]              INT             NULL,
    [SocialClicks]              INT             NULL,
    [SocialUniqueClicks]        INT             NULL,
    [Impressions]               INT             NULL,
    [UniqueImpressions]         INT             NULL,
    [SocialImpressions]         INT             NULL,
    [SocialUniqueImpressions]   INT             NULL,
    [Actions]                   INT             NULL,
    [Connections]               INT             NULL
);

