CREATE TABLE [dbo].[BackEnd] (
    [AccountID]             BIGINT        NULL,
    [ChannelID]             BIGINT        NULL,
    [GenericTarget1GK]      BIGINT        NULL,
    [GenericTarget2GK]      BIGINT        NULL,
    [GenericTarget3GK]      BIGINT        NULL,
    [GenericTargetMatch1GK] BIGINT        NULL,
    [GenericTargetMatch2GK] BIGINT        NULL,
    [GenericTargetMatch3GK] BIGINT        NULL,
    [CustomSegment1GK]      BIGINT        NULL,
    [CustomSegment2GK]      BIGINT        NULL,
    [CustomSegment3GK]      BIGINT        NULL,
    [CustomSegment4GK]      BIGINT        NULL,
    [CustomSegment5GK]      BIGINT        NULL,
    [CustomSegment6GK]      BIGINT        NULL,
    [CustomSegment7GK]      BIGINT        NULL,
    [CustomSegment8GK]      BIGINT        NULL,
    [CustomSegment9GK]      BIGINT        NULL,
    [CustomSegment10GK]     BIGINT        NULL,
    [TargetPeriodStart]     DATETIME      NULL,
    [TargetPeriodEnd]       DATETIME      NULL,
    [Currency]              NVARCHAR (10) NULL,
    [OutputID]              CHAR (32)     NULL,
    [ClientSpecific1]       FLOAT (53)    NULL,
    [ClientSpecific2]       FLOAT (53)    NULL,
    [ClientSpecific3]       FLOAT (53)    NULL,
    [ClientSpecific4]       FLOAT (53)    NULL,
    [ClientSpecific5]       FLOAT (53)    NULL,
    [ClientSpecific6]       FLOAT (53)    NULL,
    [ClientSpecific7]       FLOAT (53)    NULL,
    [ClientSpecific8]       FLOAT (53)    NULL,
    [ClientSpecific9]       FLOAT (53)    NULL,
    [ClientSpecific10]      FLOAT (53)    NULL,
    [ClientSpecific11]      FLOAT (53)    NULL,
    [ClientSpecific12]      FLOAT (53)    NULL,
    [ClientSpecific13]      FLOAT (53)    NULL,
    [ClientSpecific14]      FLOAT (53)    NULL,
    [ClientSpecific15]      FLOAT (53)    NULL,
    [ClientSpecific16]      FLOAT (53)    NULL,
    [ClientSpecific17]      FLOAT (53)    NULL,
    [ClientSpecific18]      FLOAT (53)    NULL,
    [ClientSpecific19]      FLOAT (53)    NULL,
    [ClientSpecific20]      FLOAT (53)    NULL
);

