CREATE TABLE [dbo].[SocialChannel] (
    [AccountID]               BIGINT        NULL,
    [ChannelID]               BIGINT        NULL,
    [AdGK]                    BIGINT        NULL,
    [AdgroupGK]               BIGINT        NULL,
    [CampaignGK]              BIGINT        NULL,
    [AdCreative1GK]           BIGINT        NULL,
    [AdCreative2GK]           BIGINT        NULL,
    [AdCreative3GK]           BIGINT        NULL,
    [AdTarget1GK]             BIGINT        NULL,
    [ADTarget2GK]             BIGINT        NULL,
    [ADTarget3GK]             BIGINT        NULL,
    [AdTargetMatch1GK]        BIGINT        NULL,
    [AdTargetMatch2GK]        BIGINT        NULL,
    [AdTargetMatch3GK]        BIGINT        NULL,
    [CustomSegment1GK]        BIGINT        NULL,
    [CustomSegment2GK]        BIGINT        NULL,
    [CustomSegment3GK]        BIGINT        NULL,
    [CustomSegment4GK]        BIGINT        NULL,
    [CustomSegment5GK]        BIGINT        NULL,
    [CustomSegment6GK]        BIGINT        NULL,
    [CustomSegment7GK]        BIGINT        NULL,
    [CustomSegment8GK]        BIGINT        NULL,
    [CustomSegment9GK]        BIGINT        NULL,
    [CustomSegment10GK]       BIGINT        NULL,
    [TargetPeriodStart]       DATETIME      NULL,
    [TargetPeriodEnd]         DATETIME      NULL,
    [Currency]                NVARCHAR (10) NULL,
    [OutputID]                CHAR (32)     NULL,
    [AveragePosition]         FLOAT (53)    NULL,
    [Cost]                    FLOAT (53)    NULL,
    [Clicks]                  INT           NULL,
    [Impressions]             INT           NULL,
    [SocialImpressions]       INT           NULL,
    [SocialClicks]            INT           NULL,
    [SocialCost]              FLOAT (53)    NULL,
    [Actions]                 INT           NULL,
    [UniqueImpressions]       INT           NULL,
    [SocialUniqueImpressions] INT           NULL,
    [UniqueClicks]            INT           NULL,
    [SocialUniqueClicks]      INT           NULL,
    [Connections]             INT           NULL
);

