CREATE TABLE [dbo].[2_Metrics] (
    [AccountID]                                 INT        NULL,
    [ChannelID]                                 INT        NULL,
    [TimePeriodStart]                           DATETIME   NULL,
    [TimePeriodEnd]                             DATETIME   NULL,
    [Ad_gk]                                     BIGINT     NOT NULL,
    [Ad_type]                                   INT        NOT NULL,
    [Campaign_gk]                               BIGINT     NOT NULL,
    [Campaign_type]                             INT        NOT NULL,
    [AdGroup_gk]                                BIGINT     NOT NULL,
    [AdGroup_type]                              INT        NOT NULL,
    [Tracker_gk]                                BIGINT     NOT NULL,
    [Tracker_type]                              INT        NOT NULL,
    [Ad_CreativeDefinition_gk]                  BIGINT     NOT NULL,
    [Ad_CreativeDefinition_type]                INT        NOT NULL,
    [CompositeCreativeDefinition_Creative_gk]   BIGINT     NOT NULL,
    [CompositeCreativeDefinition_Creative_type] INT        NOT NULL,
    [TitleDefinition_gk]                        BIGINT     NOT NULL,
    [TitleDefinition_type]                      INT        NOT NULL,
    [Desc1Definition_gk]                        BIGINT     NOT NULL,
    [Desc1Definition_type]                      INT        NOT NULL,
    [Desc2Definition_gk]                        BIGINT     NOT NULL,
    [Desc2Definition_type]                      INT        NOT NULL,
    [TitleCreative_gk]                          BIGINT     NOT NULL,
    [TitleCreative_type]                        INT        NOT NULL,
    [Desc1Creative_gk]                          BIGINT     NOT NULL,
    [Desc1Creative_type]                        INT        NOT NULL,
    [Desc2Creative_gk]                          BIGINT     NOT NULL,
    [Desc2Creative_type]                        INT        NOT NULL,
    [Impressions]                               FLOAT (53) NOT NULL,
    [Clicks]                                    FLOAT (53) NOT NULL,
    [Cost]                                      FLOAT (53) NOT NULL
);

